image: docker:latest

services:
  - docker:dind

variables:
  DOCKERFILE_FLAVOUR: debian
  PHP_BASE_IMAGE_VERSION: fpm
  PHP_IMAGE_NAME: o2system/docker
  TEST_O2SYSTEM_VERSION: v5.1.239

before_script:
  - apk add --no-cache python py2-pip git
  - pip install --no-cache-dir docker-compose==1.16.0
  - git clone https://github.com/o2system/o2system _host-volumes/o2system
  - pushd _host-volumes/o2system && git checkout ${TEST_O2SYSTEM_VERSION} && popd
  - cp .env-dist .env
  - docker info

build:
  environment:
    name: ${DOCKERFILE_FLAVOUR}/php-${PHP_BASE_IMAGE_VERSION}
  script:
    - docker-compose build
    - docker-compose run --rm php php -v
    # - docker-compose run --rm php php /tests/requirements.php
    - docker-compose run --rm -w /o2system php composer install
    # - docker-compose run --rm -w /o2system php php -d error_reporting="E_ALL ^ E_DEPRECATED" vendor/bin/phpunit tests/framework/ --exclude db
